-- migrate:up

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA public;

CREATE SCHEMA IF NOT EXISTS gitlab_mr_api;

CREATE FUNCTION gitlab_mr_api.uuid_generate_v7() RETURNS uuid
    LANGUAGE plpgsql PARALLEL SAFE
    AS $$
  DECLARE
    unix_time_ms CONSTANT bytea NOT NULL DEFAULT substring(int8send((extract(epoch FROM clock_timestamp()) * 1000)::bigint) from 3);
    buffer                bytea NOT NULL DEFAULT unix_time_ms || public.gen_random_bytes(10);
  BEGIN
    buffer = set_byte(buffer, 6, (b'0111' || get_byte(buffer, 6)::bit(4))::bit(8)::int);
    buffer = set_byte(buffer, 8, (b'10'   || get_byte(buffer, 8)::bit(6))::bit(8)::int);
    RETURN encode(buffer, 'hex');
  END
$$;

CREATE TABLE gitlab_mr_api.gitlab_instance (
    gitlab_instance_id bigint NOT NULL,
    hostname character varying NOT NULL
);

ALTER TABLE gitlab_mr_api.gitlab_instance ALTER COLUMN gitlab_instance_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME gitlab_mr_api.gitlab_instance_gitlab_instance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE gitlab_mr_api.merge_request_ref (
    merge_request_ref_id bigint NOT NULL,
    gitlab_instance_id bigint NOT NULL,
    gitlab_project_id bigint NOT NULL,
    gitlab_merge_request_id bigint NOT NULL,
    gitlab_merge_request_iid bigint NOT NULL,
    merge_request_payload jsonb DEFAULT '{}'::jsonb,
    merge_request_extra_state jsonb DEFAULT '{}'::jsonb,
    head_pipeline_id bigint,
    merge_request_ref_uuid uuid DEFAULT gitlab_mr_api.uuid_generate_v7() NOT NULL
);

COMMENT ON COLUMN gitlab_mr_api.merge_request_ref.gitlab_merge_request_id IS 'merge request id instance wide';
COMMENT ON COLUMN gitlab_mr_api.merge_request_ref.gitlab_merge_request_iid IS 'merge request id project scoped (used for links etc)';

ALTER TABLE gitlab_mr_api.merge_request_ref ALTER COLUMN merge_request_ref_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME gitlab_mr_api.merge_request_ref_merge_request_ref_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE gitlab_mr_api.merge_request_message_ref (
    merge_request_message_ref_id bigint NOT NULL,
    merge_request_ref_id bigint NOT NULL,
    conversation_token uuid NOT NULL,
    message_id uuid,
    failure jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone
);

ALTER TABLE gitlab_mr_api.merge_request_message_ref ALTER COLUMN merge_request_message_ref_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME gitlab_mr_api.merge_request_message_ref_merge_request_message_ref_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE gitlab_mr_api.msg_to_delete (
    msg_to_delete_id bigint NOT NULL,
    message_id character varying NOT NULL,
    expire_at timestamp with time zone DEFAULT (now() + '00:05:00'::interval) NOT NULL
);

ALTER TABLE gitlab_mr_api.msg_to_delete ALTER COLUMN msg_to_delete_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gitlab_mr_api.msg_to_delete_msg_to_delete_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY gitlab_mr_api.gitlab_instance
    ADD CONSTRAINT gitlab_instance_pkey PRIMARY KEY (gitlab_instance_id);

ALTER TABLE ONLY gitlab_mr_api.merge_request_message_ref
    ADD CONSTRAINT merge_request_message_ref_pkey PRIMARY KEY (merge_request_message_ref_id);

ALTER TABLE ONLY gitlab_mr_api.merge_request_ref
    ADD CONSTRAINT merge_request_ref_mr_identity_uniq UNIQUE (gitlab_instance_id, gitlab_project_id, gitlab_merge_request_iid);

ALTER TABLE ONLY gitlab_mr_api.merge_request_ref
    ADD CONSTRAINT merge_request_ref_pkey PRIMARY KEY (merge_request_ref_id);

ALTER TABLE ONLY gitlab_mr_api.merge_request_message_ref
    ADD CONSTRAINT mr_ref_conv_token_uniq UNIQUE (merge_request_ref_id, conversation_token);

ALTER TABLE ONLY gitlab_mr_api.msg_to_delete
    ADD CONSTRAINT msg_to_delete_pkey PRIMARY KEY (msg_to_delete_id);

CREATE UNIQUE INDEX gitlab_instance_hostname_lower_uniq ON gitlab_mr_api.gitlab_instance USING btree (lower((hostname)::text));

-- migrate:down

DROP INDEX IF EXISTS gitlab_mr_api.gitlab_instance_hostname_lower_uniq;
DROP TABLE IF EXISTS gitlab_mr_api.msg_to_delete;
DROP TABLE IF EXISTS gitlab_mr_api.merge_request_message_ref;
DROP TABLE IF EXISTS gitlab_mr_api.merge_request_ref;
DROP TABLE IF EXISTS gitlab_mr_api.gitlab_instance;
DROP FUNCTION IF EXISTS gitlab_mr_api.uuid_generate_v7();
DROP SCHEMA IF EXISTS gitlab_mr_api;
